a=input("enter a string : ")
print(a)
print(len(a))
print(a[0:7])
print(a[-7:-1])
print(a[0:7]+a[-7:-1])
print(str.capitalize(a))
print(str.upper(a))
print(str.lower(a))
print(str.replace(a, " ", "_"))
print(str.split(a))
print(str.split(a, " "))
print(str.split(a, " ")[0])
print(str.count(a, " "))
print(str.endswith(a, "e"))
print(str.startswith(a, "t"))
print(str.find(a, " "))
print(str.rfind(a, " "))